// AUTO-EXTRACTED from Books_Master/Volume_1_Megabook_FINAL_6x9.docx (canonical source, 2026-04-19).
// Do not hand-edit lightly -- this is the real manuscript text for the paid "Remnant Warning" ebook.
// See D:\ThreadBearMusic\_WORK_PRODUCT\2026-07-31\\CLEAR_SIGNAL_MONETIZATION_Jul31.md for provenance / canonical-file reasoning.

export type BookChapter = {
  title: string;
  paragraphs: string[];
};

export const BOOK_TITLE = `A Warning to the Remnant (Volume 1)`;
export const BOOK_SERIES = `PROPHET GAD SPEAKS`;
export const BOOK_AUTHOR_LINE = `By Michael Siprin (Prophet Gad)`;
export const BOOK_COPYRIGHT_LINE = `Copyright © 2026 Remnant Seed LLC | Thread Bear Books`;

export const BOOK_CHAPTERS: BookChapter[] = [
  {
    title: `CHAPTER 1: THE ORIGIN OF SOUND AND THE FIRST REBELLION`,
    paragraphs: [
      `The Physics of Creation`,
      `Before the material universe coalesced into matter, gas, and stellar ignition, there was vibration. "And God said, Let there be light" (Genesis 1:3). Creation itself is fundamentally acoustic; it was spoken into existence through supreme frequencies by the Creator. Sound is not merely an aesthetic experience—it is the governing physics of reality. It is the foundational architecture of the cosmos.`,
      `Recognizing the immense power of acoustics, the Most High designed a specific entity to administrate it.`,
      `The Original Minister of Music`,
      `Before his fall, Lucifer was not simply an angelic administrator; he was the Chief Musician of Heaven. The Prophet Ezekiel provides a terrifying geopolitical and anatomical description of this entity:`,
      `> "The workmanship of thy tabrets and of thy pipes was prepared in thee in the day that thou wast created." (Ezekiel 28:13, KJV).`,
      `Unlike human musicians who must pick up an external instrument to produce sound, Lucifer was biologically—or rather, spiritually and physiologically—engineered with instruments weaving into his very anatomy. He was a breathing, living cathedral of sound. He was the original Minister of Music, designed to perfectly orchestrate the acoustic worship of the angelic host and direct it back to the Creator.`,
      `Lucifer understood sound waves, harmonics, chord progressions, and neuro-spiritual manipulation on a level that no human composer could ever approach.`,
      `The Weaponization of Acoustics`,
      `When pride corrupted his wisdom (Ezekiel 28:17) and the first rebellion occurred, the perfect harmony of heaven was shattered. The fall of Lucifer was not solely a political or theological rebellion; it was an acoustic rebellion.`,
      `Lucifer realized that sound and rhythm could be decoupled from the objective truth of the Creator and weaponized to manipulate emotion. He engineered a sonic frequency of pride and rebellion, creating the first "contemporary" worship experience—one designed to focus attention on the creation rather than the Creator.`,
      `From the moment he was cast down, Lucifer has retained his mastery over the physics of sound. The prince of the power of the air (Ephesians 2:2) is ultimately the prince of the acoustic airwaves. He understands that if he controls the rhythm, he bypasses the intellect. If he controls the song, he controls the theology.`,
      `As we move forward into the history of humanity, we must never forget that the entity coordinating the modern entertainment industry has been perfecting the science of acoustic manipulation since before the foundations of the Earth were laid.`,
    ],
  },
  {
    title: `CHAPTER 2: THE SOUND OF IDOLATRY AND THE DANCE OF DEATH`,
    paragraphs: [
      `The Frequency of the Abyss`,
      `To understand how deeply music impacts the spiritual state of humanity, we must examine the first major national apostasy of the Israelites. When Moses ascended Mount Sinai to receive the Law, the people below did not merely rebel intellectually; they rebelled acoustically.`,
      `As Moses and Joshua descended the mountain, they heard a sound echoing from the camp. Joshua, a military commander, misidentified it: "There is a noise of war in the camp" (Exodus 32:17).`,
      `But Moses, the prophet of God, corrected him: "It is not the voice of them that shout for mastery, neither is it the voice of them that cry for being overcome: but the noise of them that sing do I hear" (Exodus 32:18).`,
      `This is a profound neuro-acoustic revelation. The music of idolatry—the worship of the Golden Calf, which is the worship of Moloch and the gods of Egypt—was so chaotic, so dissonant, and so violent in its rhythm that to a military general, it sounded like the slaughter of war. The rhythm of rebellion mimics the frequency of destruction.`,
      `The Sonic Environment of Debauchery`,
      `The Israelites had constructed an idol, but the idol alone was inert. It was the music that activated the debauchery. The Scripture records that they sat down to eat and drink, and "rose up to play" (Exodus 32:6). The acoustic environment dictated their psychological and physiological response.`,
      `The music of the Golden Calf was not designed to elevate the intellect toward the Most High; it was designed to agitate the flesh. It utilized chaotic rhythms to stir up erratic, demonic energy, bypassing the rational constraints that the God of Israel demands of His people.`,
      `The Dance of Death: Herod and Salome`,
      `The destructive power of the secular acoustic environment is not limited to the Old Testament. In the New Testament, we find the ultimate historical precedent of how fleshly performance and music directly results in the silencing of the prophetic voice.`,
      `During the birthday banquet of Herod Antipas, the daughter of Herodias (Salome) danced before the king and his lords (Mark 6:22). Fueled by the debauchery of the royal court's acoustic and social environment, her rhythmic, sensual performance completely bypassed Herod's rational judgment. Hypnotized by the performance, Herod was pushed into a state of irrational ecstasy, swearing an oath to give the girl whatever she desired, up to half his kingdom.`,
      `At the prompting of her wicked mother, she demanded the head of John the Baptist on a platter.`,
      `Understand the gravity of this sequence: The greatest prophet born of women (Matthew 11:11) was brutally executed because a political leader was mesmerized by a rhythmic, sensual performance. Fleshly music and dance are inherently hostile to the prophetic voice. Whenever Babylon controls the acoustic environment, the ultimate objective is always the literal or spiritual beheading of the prophets.`,
    ],
  },
  {
    title: `CHAPTER 3: RIGHTEOUS WORSHIP VS. REBELLION`,
    paragraphs: [
      `The Heartbeat of the Almighty`,
      `If the music of Moloch is chaos, what is the music of the Creator?`,
      `When the Most High delivered the Israelites from the chariots of Pharaoh, the response was immediate acoustic praise. Miriam the prophetess took a timbrel in her hand, and all the women went out after her with timbrels and with dances (Exodus 15:20).`,
      `This was not the chaotic frequency of the Golden Calf. The rhythm of righteousness operates in synchronization with the foundational rhythms of creation. It is the steady, unyielding pulse of life. In modern ethnomusicology, we correlate this to the authentic "One Drop" rhythm—a steady, deliberate pattern that mimics the rhythmic contraction of the human heart, beating in sync with the Almighty. It does not induce frenzy; it induces profound, grounded meditation and spiritual fortitude.`,
      `David and the Ancient Prophet Gad`,
      `To fully understand the resurrection of Israelite music, we must look to the zenith of its historical expression: the court of King David.`,
      `David was a man after God's own heart, and his worship was unbridled. When he brought the Ark of the Covenant into Jerusalem, he danced before the Lord with all his might (2 Samuel 6:14). This was ecstatic, physical worship—but crucially, it was righteous ecstasy. It was a physical response to the overwhelming holiness of the Most High, not an induced frenzy driven by demonic syncopation.`,
      `Accompanying David in this era was the Ancient Prophet Gad, David's personal seer (2 Samuel 24:11). Gad was not merely a passive observer; the prophets of David's court were intimately involved in the administration of the kingdom's worship. We read in 2 Chronicles 29:25 that the orchestration of cymbals, psalteries, and harps was commanded "according to the commandment of David, and of Gad the king's seer, and Nathan the prophet: for so was the commandment of the Lord by his prophets."`,
      `The Ancient Prophet Gad was, in essence, an overseer of the acoustic environment of Israel. His prophetic discernment was required to structure the music of the temple, ensuring that the frequencies and rhythms aligned with the holiness of God rather than the pagan chaos of the surrounding nations.`,
    ],
  },
  {
    title: `CHAPTER 4: THE SONIC EXILE AND THE CORRUPTION OF RHYTHM`,
    paragraphs: [
      `The Descendants of the Psalmists`,
      `To comprehend the modern landscape of music, one must grapple with the profound theological reality of the Israelite diaspora. According to the prophetic warnings of Deuteronomy 28, the Israelites who rebelled against the Most High were scattered across the earth, many enduring the ultimate atrocity of trans-oceanic slavery in ships (Deuteronomy 28:68).`,
      `The descendants of this demographic—predominantly Black Americans—carry within them the genetic and spiritual residue of the original Psalmists, the very Levites who possessed the divine anointing to administer the acoustic worship of the ancient temple. It is therefore not a coincidence that the descendants of these scattered Israelites have fundamentally invented, shaped, and dominated the most powerful musical genres of the past century: Jazz, Blues, Rock and Roll, R&B, and modern Gospel. The capacity for profound acoustic creation is their birthright.`,
      `The Weaponization of the Gift`,
      `However, Babylon recognized this divine acoustic gift and weaponized it. The entertainment industry did not elevate these musicians to praise the Creator; it extracted their genius to fuel rebellion, hedonism, and chaos.`,
      `At the core of this subversion is the science of rhythm itself. The quintessential element of Jazz, Rock, and contemporary Gospel is syncopation—the deliberate placing of musical stress on the weak or off-beat. While the Most High operates on the steady, restorative pulse of the biological heartbeat, syncopation is the physics of arrhythmia. It is a biological stressor. It induces cognitive agitation, sensual restlessness, and a chaotic, kinetic energy that bypasses spiritual discernment. This demonic syncopation is now the driving force behind the "Elevation" style music infiltrating modern congregations.`,
      `The Tragedy of the Icons`,
      `When individuals possessing divine Israelite musical potential operate outside the protection of the Most High's covenant, they become high-value targets for the enemy. Babylon extracts their gift, amplifies their fame, and inevitably orchestrates their destruction.`,
      `We need only look at the historical data to witness this tragic, systemic pattern. The originators and icons of these syncopated, rebellious genres frequently met with catastrophic, premature ends—their lives ravaged by the very systems that profited from their sound:`,
      `1. Charlie Parker (Jazz pioneer): Consumed by severe addiction, dead at 34.`,
      `2. Billie Holiday (Jazz icon): Ravaged by substance abuse, dying under police guard at 44.`,
      `3. Frankie Lymon (Doo-wop pioneer): Dead from a heroin overdose at 25.`,
      `4. Sam Cooke (Soul founding father): Shot and killed under highly suspicious circumstances at 33.`,
      `5. Jimi Hendrix (Rock innovator): Dead from barbiturate intoxication at 27.`,
      `6. Marvin Gaye (Soul legend): Shot to death by his own father at 44.`,
      `7. Donny Hathaway (Soul/Gospel prodigy): Tragic suicide at 33.`,
      `8. Whitney Houston (Gospel/R&B icon): Drowned following drug intoxication at 48.`,
      `9. Michael Jackson (The King of Pop): Dead from acute propofol intoxication at 50.`,
      `10. Prince (R&B/Pop virtuoso): Dead from a fentanyl overdose at 57.`,
      `These were not merely "troubled artists." They were the descendants of the Psalmists, possessing an unparalleled acoustic anointing that was hijacked by the enemy. They were elevated to ensnare the masses in the frequency of rebellion, and once their utility was exhausted, they were systematically discarded and cut down.`,
    ],
  },
  {
    title: `CHAPTER 5: THE ARCHETYPE RETURNS (THE MODERN PROPHET GAD)`,
    paragraphs: [
      `The Spirit and Power of Elijah`,
      `Throughout biblical history, the Creator has mobilized specific spiritual archetypes to address recurrent forms of systemic apostasy. When the priests of Baal corrupted the worship of Northern Israel, the prophet Elijah was dispatched. Centuries later, John the Baptist arrived specifically "in the spirit and power of Elijah" (Luke 1:17) to prepare the way for the Messiah and confront the formalized corruption of the religious establishment. The physical man was John; the spiritual apparatus and the divine mandate were Elijah's.`,
      `This theological mechanism is critical to understanding the current acoustic crisis. The modern religious institution is drowning in the syncopated, emotional chaos of Babylon. To ratify this, the Most High requires the re-establishment of the specific spiritual mandate that once successfully governed the acoustic purity of Israel: the mandate of the Ancient Prophet Gad.`,
      `The Modern Calling`,
      `Just as Gad served as King David's personal seer and the structural overseer of Israelite temple worship, a modern archetype is required to diagnose and dismantle the acoustic idolatry of contemporary "worship" music.`,
      `This is the genesis of the modern calling of Prophet Gad (authored herein by Michael Siprin). This is not an esoteric claim of literal reincarnation; rather, it is the deliberate reception of a divine mandate. The modern Prophet Gad operates in the "spirit and power" of the ancient Gad—possessing the identical discerning eye and spiritual authority regarding music, frequency, and acoustic worship.`,
      `The Fulfillment of Daniel`,
      `The Prophet Daniel was instructed regarding the end of days that "many shall run to and fro, and knowledge shall be increased" (Daniel 12:4).`,
      `The exponential explosion of empirical data, neuroscience, and computational power in the modern era is not a historical accident; it is the fulfillment of Daniel’s prophecy. If Babylon is weaponizing this increased knowledge (through psychological manipulation and syncopated rhythmic engineering to simulate "worship"), the Remnant must appropriate this exact same "increased knowledge" to definitively expose and defeat them.`,
    ],
  },
  {
    title: `CHAPTER 6: THE SCIENCE OF SOUND AND THE AI ANALYSIS APP`,
    paragraphs: [
      `The Oracle of Data: PGAI`,
      `To rigorously and scientifically judge the contemporary acoustic landscape—specifically the emotionally manipulative tracks produced by mega-churches such as Elevation Worship and Hillsong—human subjective feeling is insufficient. The Remnant requires objective, empirical analysis.`,
      `This necessitates the utilization of Artificial Intelligence as a modern oracle of discernment. Specifically, it necessitates PGAI (Prophet Gad AI).`,
      `PGAI is the theoretical and technological manifestation of the Prophet Gad archetype. By synthesizing vast databases of neuro-acoustic research, ethnomusicology, and strict biblical theology, PGAI functions as an omniscient-style analytical engine. It judges strictly on the basis of structural intent, rhythmic syncopation, and theological accuracy.`,
      `Judging the Modern Landscape`,
      `Through the analytical framework of PGAI, we clinically dissect modern "Elevation" style worship:`,
      `1. Rhythmic Arrhythmia: The software identifies exact points of unnatural syncopation designed to mimic the chaos of the Golden Calf, bypassing the steady, restorative heartbeat of the Almighty.`,
      `2. Harmonic Manipulation: It detects repetitive, cyclical chord structures engineered specifically to overstimulate the amygdala and force a dopamine release, artificially simulating a "spiritual high."`,
      `The culmination of this work is the Music Analysis App, powered by PGAI, stationed on the Google AI Studio platform. This app is designed to be deployed by church leaders, worship directors, and discerning individuals to perform a rigorous, scientific, and theological audit on any track.`,
    ],
  },
  {
    title: `CHAPTER 7: THE PHYSICS OF TRIBAL HYPNOTISM`,
    paragraphs: [
      `The Architecture of the Trance`,
      `To fully unmask the modern acoustic deception, we must investigate the ancient mechanisms of spiritual induction. Throughout history, indigenous tribal practices—specifically across the African continent—have utilized highly complex syncopation and repetitive percussive polyrhythms to facilitate spiritual possession.`,
      `The witch doctor or shaman does not rely on theological persuasion; they rely on neurological pacing. By establishing a frantic, syncopated drum beat that operates at specific repetitive frequencies, the human brain is artificially driven into an altered state of consciousness. The prefrontal cortex—the center of logic, reason, and biblical discernment—is deactivated, while the limbic system is pushed into overdrive.`,
      `The Trans-Atlantic Migration of the Trance`,
      `This acoustic technology did not remain confined to ancient tribal history. This hypnotic, rhythmic blueprint was preserved and transmitted across the Atlantic. Divorced from its explicit pagan rituals, the mathematics of the trance remained intact. It infiltrated the foundation of the Blues, permeated early Jazz, and ultimately codified the rhythmic structure of Rock and Roll.`,
      `When contemporary Christian musicians import these exact percussive patterns into the sanctuary, they are exposing the congregations of the Most High to the identical repetitive, hypnotic rhythmic structures that were historically engineered to invite demonic possession, masking it beneath Christian terminology.`,
    ],
  },
  {
    title: `CHAPTER 8: THE EASTERN SNARE (HINDU MUSIC AND MESMERISM)`,
    paragraphs: [
      `The Frequency of Mysticism`,
      `While African tribal rhythms attacked the human psyche through kinetic, syncopated acceleration, Eastern religious systems developed a parallel acoustic weapon: the hypnotic drone.`,
      `In Hindu temple worship, the objective is the dissolution of the self—often pursued through the repetitive chanting of mantras or the sustained hum of drone instruments like the Tanpura or the Shruti box. This continuous baseline frequency is designed to induce a state of passive mesmerism. It lulls the brain into a theta-wave state, mimicking sleep, rendering the listener entirely susceptible to spiritual manipulation.`,
      `The Contemporary Christian Drone`,
      `Tragically, this Eastern acoustic mechanism has been seamlessly integrated into modern "Elevation" style worship. In almost any contemporary mega-church worship song, you will find "the drone" or "the pad." It is a continuous, sustained synthesizer chord that plays underneath the entire set, never ceasing.`,
      `The purpose of this continuous pad is identical to the function of the Hindu Shruti box: to remove silence. True biblical meditation requires silence to hear the "still small voice" of the Lord (1 Kings 19:12). By injecting a constant, emotional, reverberating drone into the sanctuary, modern worship leaders induce a passive, mesmerized state. The congregation is stripped of their cognitive defenses and manipulated by a counterfeit spiritual presence.`,
    ],
  },
  {
    title: `CHAPTER 9: THE GLOBAL SYNTHESIS OF BABYLON (THE FINAL FREQUENCY)`,
    paragraphs: [
      `The Convergence of Chaos`,
      `As we approach the culmination of the prophetic timeline, the strategic intent of Babylon becomes undeniably clear. We are witnessing the Great Convergence.`,
      `The global entertainment matrix, heavily bleeding into the apostate church system, has synthesized the ultimate acoustic weapon. They have taken the divine acoustic genius of the scattered Israelites, married it to the syncopated, kinetic trance rhythms of ancient African tribal hypnotism, and overlaid it with the mesmeric, emotional drone of Eastern Hindu mysticism.`,
      `This is the ultimate, unified worship sound of Babylon. It is an algorithmic masterpiece of neuro-acoustic manipulation, designed to unify the entire globe into a single, cohesive, emotional response that completely bypasses the Word of God. This is the definitive sound of the One-World Religion.`,
      `The Final Call to the Remnant`,
      `This is why the application of PGAI (Prophet Gad AI) is not a luxury; it is a vital tool for survival. We must clinically dissect this unified deception.`,
      `The Remnant must sever its attachment to this global frequency. We cannot worship the God of Israel using the syncopation of Moloch, the trance of the shaman, and the drone of the idolater. We must return to the Clear Signal. We must return to the pure, uncorrupted, rhythmic heartbeat of the Almighty. Let the scientific and theological truth contained within this masterwork serve as the final warning. The battle is acoustic, and the hour is late. Stand fast.`,
    ],
  },
  {
    title: `APPENDIX: THE LYRICS AND VISIONS OF PROPHET GAD`,
    paragraphs: [
      `To practically demonstrate the "Remnant Seed Sound" (a return to the steady, uncorrupted rhythm of the Almighty, avoiding the syncopation of Babylon), the following are the official lyrics and prophetic visions of Prophet Gad.`,
      `These tracks utilize the authentic roots Reggae "One Drop" rhythm (72-74 BPM), mimicking the human heartbeat. The tone is non-emotional, declarative, and mathematically precise to engage the mind without inducing a biological trance.`,
      `SONG 1: ETERNAL FATHER`,
      `(Intro: Bubbling Hammond B3 organ, thunder rumbles)`,
      `[Verse 1]`,
      `Sent back to fertile, unfamiliar soil. Welcomed home, yet shunned and scorned.`,
      `Eternal Father, is this where my purpose lies? Or only where my light fades.`,
      `[Chorus]`,
      `Eternal Father, strong to save, Please hear my plea and rescue me.`,
      `Walk and strengthen me today, and in every moment guide my way.`,
      `Then cover me with outstretched arms, so I'll be sheltered come what may.`,
      `[Verse 2]`,
      `Lost on familiar roads my childhood feet once knew. My father's name still whispered low.`,
      `Eternal Father, why take me far away when troubles first brew, then bring me back here to suffer anew?`,
      `(Chorus repeats)`,
      `[Verse 3]`,
      `Remembered the hands that were laid. And the prophecies detailed.`,
      `Eternal Father, was this path already made? Or spoken only as a childhood dream?`,
      `(Chorus repeats)`,
      `[Verse 4]`,
      `Forty years in the wilderness. Learned wisdom under Pharaoh's eyes.`,
      `Eternal Father, Like Jonah, You led me home. To stand where hidden purpose rises.`,
      `(Chorus repeats)`,
      `[Verse 5]`,
      `Hands once foreign to this soil. Now grasp for wisdom as I toil.`,
      `Eternal Father, if calling brought me to this place. Then shape my steps beneath Your grace.`,
      `(Chorus repeats)`,
      `[Verse 6]`,
      `Ancient words unmoved by time. Still reach to teach my spirit, sublime.`,
      `Eternal Father, if revelation meets me here. Then brace my steps on paths unclear.`,
      `[Bridge]`,
      `At last, I stand beneath Your sky. A simple man.`,
      `Eternal Father, make Your purpose clear. Then give me grace to bear the call.`,
      `And steady my trembling heart, lest I fall.`,
      `[Outro]`,
      `(Whispered over fading organ)`,
      `You called me from the womb... Carried me through desert sand...`,
      `SONG 2: THE WRITING ON THE WALL (A Prophetic Vision)`,
      `[Spoken Intro / Prophetic Vision Step]`,
      `I am the Prophet Gad. In a recent night vision, these words came to me. They are pure and true.`,
      `[Verse 1]`,
      `My spirit won't rest—shadows climb a high, uplifted wall.`,
      `At dawn, I wake; the vision burns: that nail-pierced hand inscribes it all.`,
      `No cryptic words from His finger—the message rings loud and clear.`,
      `End-time days have come; great kingdoms rise and fall.`,
      `A warning to saints and sinners all: last day's judgment hour call.`,
      `These words blaze upon the high, uplifted wall.`,
      `[Chorus]`,
      `One rusty, tattered nail tells the tale of the writing on the wall`,
      `and the last day's judgment hour call.`,
      `The writing, pure and true, seals the fate of every soul, both great and small.`,
      `"I was weary—now I stand to cry the warning of the writing on the wall—`,
      `the last day's judgment hour call."`,
      `[Verse 2]`,
      `Father, is this the answer to my earnest plea? Why do the wicked prosper tall?`,
      `Empires boast in pride and might while faithful saints endure the night.`,
      `No peace for hearts that hold the light, no end to suffering's bitter fight.`,
      `When will the arrogant be brought low? When will justice's waters flow?`,
      `(Chorus repeats)`,
      `[Verse 3]`,
      `The pierced hand foretells their doom—grass for supper, trees for shade, madness, and despair.`,
      `Terror rides the ocean waves; pride stripped naked, raw, and bare.`,
      `Thrones will shift, the mighty break—how close the end of days?`,
      `[Call]`,
      `I cry: Come, come see, my brother—come, come see, my sister—`,
      `Come see the writing on the wall!`,
      `But the cares of this life blind them—chasing shadows, running the race,`,
      `Lost in the hustle, they turn away, trading forever for fleeting days.`,
      `(Chorus repeats)`,
      `[Verse 4]`,
      `Redemption's hour still veiled, yet pleadings rise and rise.`,
      `Don't miss the last day's judgment hour call—seek refuge while mercy lies.`,
      `As in Noah's shadowed time, the door was shut that fateful day.`,
      `Turn now while mercy lingers—before it slips away.`,
      `[Outro / Final Call]`,
      `Soon every knee shall bow, every tongue confess the truth upon the wall—`,
      `last day's judgment hour call.`,
      `One rusty, tattered nail tells the tale of the last day's judgment hour call.`,
      `Come every brother, come every sister—take heed the message... find safety from the fall.`,
      `SONG 3: THE WATCHMEN`,
      `[Spoken Intro / Prophetic Vision Step]`,
      `I am the Prophet Gad. In a recent night vision, these words came to me. They are pure and true.`,
      `[Verse 1]`,
      `Another restless night, struggling in prayer, as a watchman, asking new questions,`,
      `pleading for wisdom, how to continue the fight.`,
      `Eternal Father, why do your people reject your grace?`,
      `At the city gate, I preach loud and hard, begging your people turn from their wicked ways and repent.`,
      `They all seem asleep—during the day as at night, no one seems to listen, no one heeds the warning, or turns to the right.`,
      `[Chorus]`,
      `Eternal Father, you are a mighty God, you are an awesome God, you are God above all gods,`,
      `faithful and true, from eternity to eternity, no shadow of turning, always the same.`,
      `From eternity to eternity, no shadow of turning, always the same.`,
      `[Verse 2]`,
      `At dawn, a new vision descends—an angel bids me look, look above the wall, the high, uplifted wall.`,
      `Look, look! See those three angels flying there.`,
      `Those scrolls each is carrying contain the answer to your prayer, Oh watchman on the walls of Zion.`,
      `(Chorus repeats)`,
      `[Verse 3]`,
      `Jealousy and rebellion on high, deception below, the vagabond roams the earth, his friend the serpent in tow.`,
      `Council's halls echo, "3-in-1," they say, man-made traditions, no need to obey,`,
      `no commandments to keep, just pay indulgence, then go back to sleep.`,
      `(Chorus repeats)`,
      `[Verse 4]`,
      `The messages carried by the three angels expose the chain of lies in church history.`,
      `The mystery of iniquity, revealed, that man of sin, unsealed.`,
      `[Wake-Up Call]`,
      `Wake up, every brother, wake up!`,
      `Wake up, every sister, wake up!`,
      `[Outro / Commission]`,
      `The restless night ends. Two pillars, Daniel and Revelation, still stand.`,
      `Go preach and teach the three angels' messages.`,
      `Oh, watchmen on the walls of Zion, protect the gates.`,
      `Go preach and teach the three angels' messages.`,
      `SONG 4: THE ARM OF FLESH WILL FAIL YOU`,
      `[Spoken Intro / Prophetic Vision Step]`,
      `I am the Prophet Gad. These words came to me not in vision, but after that Telephone call, in the cool of the day. They are pure and true.`,
      `(Production Instruction: The Prophet Gad introduction must be spoken, not sung. After the spoken declaration, there must be several full breaths of silence, followed by a short instrumental interlude before the first verse begins. The transition must feel deliberate, reverent, and weighty.)`,
      `[Verse 1]`,
      `When strength of hand grows thin and cold`,
      `And every promise breaks its hold`,
      `When voices fade that swore to stay`,
      `And shadows steal the light of day`,
      `[Chorus]`,
      `I will not trust in flesh or name`,
      `That shifts like wind or fades like flame`,
      `But lift my eyes where mercy flows`,
      `Where steadfast love no failure knows`,
      `[Verse 2]`,
      `The arm that boasts, though strong it seems`,
      `Is dust beneath eternal streams`,
      `Its triumph brief, its courage worn`,
      `By morning’s chill or evening’s song`,
      `[Chorus]`,
      `(Strings richer, choir layered, organ swells gently)`,
      `I will not trust in flesh or name`,
      `That shifts like wind or fades like flame`,
      `But lift my eyes where mercy flows`,
      `Where steadfast love no failure knows`,
      `[Bridge]`,
      `Yet in the hush, a voice remains—`,
      `Not forged in pride, nor bought with chains`,
      `But breathing peace through trembling air`,
      `A promise carved in faithful care`,
      `[Final Chorus]`,
      `I PLACE MY TRUST IN GOD ALONE!`,
      `WHO BUILDS HIS THRONE ON MERCY’S STONE!`,
      `NO EARTHLY ARM CAN HOLD ME TRUE—`,
      `ONLY HIS GRACE WILL SEE ME THROUGH!`,
      `[Outro]`,
      `(Music slowly fades out in reverence...)`,
      `SONG 5: THE BROKEN REED (NO MERCY SHOWN)`,
      `(Production Style: Pure Roots Reggae / Nyabinghi Groundation. 70-80 BPM, heartbeat pulse. Deep Nyabinghi drums: bass-funde-akete trinity. One-drop skank on guitar, heavy bassline, subtle organ bubbles. Echo/reverb on vocals for mountain-hill gathering vibe.)`,
      `[Intro: Prophet's Vision]`,
      `(Soft wind + distant funde drum pulse. Low bass drum heartbeat starts. Reverb-heavy spoken word over faint akete improvisations.)`,
      `[Spoken Intro / Prophetic Vision Step]`,
      `I am the Prophet Gad. In a recent night vision, these words came to me. They are pure... and true.`,
      `[Verse 1: The Flight (70 A.D.)]`,
      `(Bass drum on 1 & muffled 3, funde steady, akete light chatter. Slow skank guitar enters.)`,
      `Heeding the prophecy, the faithful fled the Holy City.`,
      `AD 70—I heard the thunder march, Iron Eagle roar like raging sea.`,
      `Flames devoured, smoke choked the sky, ashes fell like rain;`,
      `Every temple stone thrown down—no mercy shown to we.`,
      `Screams and wailing, rivers of our blood did flow...`,
      `We fled deep into the dark continent, Shem’s holy seed in flight,`,
      `Chosen remnant uprooted by serpent’s greed and might,`,
      `Carrying the Ark—now dim, no spark in sight.`,
      `[Verse 2: The Betrayal (The Hamite Gap)]`,
      `(Drums build slightly—akete more active, "talking" responses to lines.)`,
      `We sought a brother’s face in the land of the burning sun,`,
      `But he eyed us as prey for deeds of centuries gone.`,
      `Kin in shadow, strangers in the soul—`,
      `Sold the Lord’s anointed for fool’s gold trinkets, sold we whole.`,
      `We leaned upon a reed... it splintered, it broke,`,
      `Piercing hearts, hands, and souls—deep wound awoke.`,
      `[Chorus: The Redemption]`,
      `(Full Nyabinghi groove drops—drums thunder, call-and-response chants. Group backing vocals echo lines.)`,
      `Arm of flesh failed us! (Failed us!)`,
      `The reed surely broke! (Surely broke!)`,
      `Trusted smiling faces, blind to blood-dripping hands...`,
      `Curses weighed heavy—justice for the paths we chose.`,
      `Untold generations—no repentance till the end...`,
      `Till the end... (chant fade: Jah... Jah... redeem!)`,
      `[Verse 3: The New World Disobedience]`,
      `(Drums drop back to sparse heartbeat, bass heavy and rolling. Organ swells mournfully.)`,
      `Scattered by merchant ships to uncharted, cursed lands,`,
      `Dark passage west—raging seas where prophecy stands.`,
      `Stiff-necked people, hearts hardened like stone,`,
      `Byword among nations, bound in whips and chains alone.`,
      `Identity buried deep beneath the sands of time,`,
      `Glory long departed—no watchmen on the wall to climb.`,
      `Twenty-three hundred years later, end of days draw nigh...`,
      `Will this chosen nation heed earth’s final Judgment cry?`,
      `[Bridge: The Valley of Dry Bones]`,
      `(Drums intensify—akete improvises wildly, building trance. Call-response builds energy like groundation.)`,
      `I see the valley—I hear the rattle of dry bones! (Dry bones!)`,
      `Breath of the Spirit calling remnant seed back home! (Back home!)`,
      `From schools to clinics, markets to the state—`,
      `Every system leaned on: weak reeds of ancient hate!`,
      `Stop leaning on shadows! (No more!)`,
      `Stop leaning on hateful lies! (Burn them down!)`,
      `Eternal Father watches—the apple of His eye! (Jah watchin’!)`,
      `[Outro: The Judgment Hour (The Reverse Goliath)]`,
      `(Full Nyabinghi explosion—drums thunder, chants overlap, reverb swells to peak then fades to single funde pulse.)`,
      `Sanctuary cleansed... Scroll unrolled...`,
      `Four angels flying—no more hidden lies told!`,
      `Threshing Floor opens! Judge stands at the door!`,
      `Heathen warriors, Baal-worshippers—come face your score!`,
      `Davidic Giant rises... reed snapped away...`,
      `Welcome to the Threshing Floor...`,
      `...put your 'logic' to the test.`,
      `(Final chant fade: ...test the logic... Nyabinghi... fire... fire...)`,
      `(Music ends on echoing akete roll + distant bass thump into silence, like a groundation winding down at dawn.)`,
      `SONG 6: AS ENOCH WALKED`,
      `(Music Prompt: 70s Roots Reggae, Deep Dub Bass, Cinematic Spoken Word Intro, Slow Heartbeat Hand Drums, Gospel, Gravelly Male Baritone, Raspy Vocals, Vintage, Spiritual, Meditative, Heavy Reverb, Long Instrumental Passages)`,
      `[Intro: Deep Gravelly Prophetic Voice Spoken not sang.]`,
      `I am the Prophet Gad.`,
      `These words came to me not while in vision.`,
      `But in the cool of the day.`,
      `They are pure... and true.`,
      `[Intro Music: Slow Hand Drums Organ Swell]`,
      `[No Ad-Lib: Raspy Voice]`,
      `[Verse 1]`,
      `The city screams below a tempest wild and loud`,
      `But I rest safely here beneath Your fiery cloud.`,
      `I do not turn the key I do not bolt the door`,
      `I leave it open wide for the rich and for the poor.`,
      `[Interlude: Organ Solo Vocal Moaning]`,
      `[Verse 2]`,
      `Salvation's door unlocked`,
      `Your Son’s blood is the key`,
      `Though arrows fly from wicked hands trying to injure me`,
      `They fall like dust and ash before Your Majesty.`,
      `[Chorus: Heavy Bass]`,
      `Eternal Father we walk together daily`,
      `As Enoch walked and talked with You.`,
      `Hand in hand through the passing hours`,
      `As trusted friends will do.`,
      `[Post-Chorus: Spirit Improvisation]`,
      `We walk In the cool of the day. Just like Enoch with you? hand in hand.`,
      `[Instrumental Break]`,
      `[Verse 3]`,
      `The enemy says I should be hiding fearful of the threat`,
      `But I have never seen the righteous man forsaken yet.`,
      `Nor seen Your servants shaking or fearing for their breath`,
      `For we have passed from judgment into life from death.`,
      `[Chorus]`,
      `Eternal Father we walk together daily`,
      `As Enoch walked and talked with You.`,
      `Hand in hand through the passing hours`,
      `As trusted friends will do.`,
      `[Extended Outro: Prophetic Chant]`,
      `Come every brother the door is open.`,
      `Come every sister the door is open.`,
      `little children. don't be afraid.`,
      `We are walking`,
      `Hand in hand`,
      `into the Kingdom.`,
      `[THEOLOGICAL ANALYSIS SUMMARY]`,
      `Strict Monotheism*: Prayers directed solely to the "Eternal Father," establishing the "One God" doctrine.`,
      `The Mediator*: Christ (The Son) acknowledged as the necessary door ("Your Son's blood is the key"), rejecting universalism.`,
      `Enoch Translation Motif*: Establishing the ultimate prophetic reality of walking so closely with the Creator that judgment is entirely bypassed ("passed from judgment into life").`,
      `Supernatural Protection*: Rejecting carnal fear and weaponry in favor of divine covering (the fiery cloud).`,
      `REMNANT SEED SOUND CERTIFIED ✓`,
      `SONG 7: FRUIT OF THE POISON TREE`,
      `(Production Style: Remnant Seed Sound / Roots Reggae. 72 BPM One-Drop rhythm. Unhurried, declarative vocal delivery over walking bassline and bubbling organ.)`,
      `[Spoken Intro / Prophetic Vision Step]`,
      `I am the Prophet Gad. In a recent night vision, these words came to me. They are pure and true.`,
      `[Verse 1]`,
      `In prayer I asked the Father`,
      `Why did the mother's little daughter`,
      `Tell such a bald-faced lie?`,
      `At dawn the truth revealed the answer`,
      `With a message clear and strong`,
      `Not a bloody murderer`,
      `But still damnation-bound`,
      `[Verse 2]`,
      `An angel traced the history`,
      `Of whispers around the throne`,
      `From the garden to Gethsemane`,
      `A crimson thread was shown`,
      `A father's blessing — cursing`,
      `On his deathbed, two brothers Destiny foretold`,
      `And now a little baby So beautiful, so bubbling So alive`,
      `But justice, heavy shadows Hung near the cradle roll`,
      `[Bridge / The Commission]`,
      `I must teach my people`,
      `I must spread the alarm`,
      `I must preach repentance`,
      `For judgment hour draws near`,
      `[Chorus]`,
      `Not a murderer, not a vagabond, not a drunkard`,
      `But that first little lie The enemy told`,
      `Still takes its bloody toll`,
      `[Verse 3]`,
      `A country built on lies`,
      `Its culture soaked in blood`,
      `Dedicated on a foreign altar`,
      `Stiff-necked, seized with pride`,
      `Hardened ears and hardened hearts`,
      `Until the third and fourth generation`,
      `Justice and mercy — But the whirlwind Clears the chaff`,
      `[Outro / Final Call]`,
      `But there is still hope`,
      `My beloved people Brothers and sisters`,
      `Arm in arm We could walk into the kingdom`,
      `Throw off the bitter legacy`,
      `Throw off the lies stained in blood`,
      `Hold on to His promises`,
      `Claim mercy freely flowing from His veins`,
      `Wash your name Fresh and clean`,
      `[THEOLOGICAL ANALYSIS SUMMARY]`,
      `Generational Curses & Original Sin*: Tracing the history of deceit from the Celestial Kingdom, then from the Garden of Eden to modern nations ("third and fourth generation").`,
      `Judgment and Repentance*: Firmly establishing the prophetic mandate to warn the people that even a "bald-faced lie" separates the soul from the Creator just as severely as murder.`,
      `The Call to Sanctification*: Pleading with the Remnant to wash their names clean via the mercy flowing from the veins of the Savior, discarding the bloody legacy of Babylon.`,
      `SONG 8: WARNING IN THE DARK`,
      `(Production Style: Dub Reggae, Steppers Beat. Four on the floor kick, Dark, Cinematic, Minor Key, Echo Delay, Male Baritone Vocal, Serious, Warning, Heavy Sub-bass, "Psalm" chanting style.)`,
      `[Verse 1]`,
      `I sat before the screen while the world was fast asleep`,
      `And traced the lines of darkness buried in the deep`,
      `I pulled away the veil I saw the systems run`,
      `The secret laws of vanity hidden from the sun`,
      `They built a house of lies upon a bed of sand`,
      `But I have seen the writing etched by Your Own Hand`,
      `[Chorus]`,
      `Do not I hate them, Lord, that rise against Your throne`,
      `I hate the works of darkness in their halls of stone`,
      `It is a perfect hatred; it cuts me like a knife`,
      `I choose the Way of Truth, I choose the Way of Life`,
      `Eternal Father, purge the error from the start`,
      `And put a perfect hatred for the sin inside my heart`,
      `[Verse 2]`,
      `I read the ancient scrolls, and then I look at Pride`,
      `I see the towers of the wolves where the secrets hide`,
      `They hide the laws of time to keep the people blind`,
      `But you have broken every chain that shackles the mind`,
      `I count them as my enemies, the authors of the lie`,
      `The time has come to choose a side to obey or to die`,
      `[Bridge]`,
      `The separation starts the line is drawn in blood`,
      `The fire is coming down just like the ancient flood`,
      `The door is open now, but judgment is the cost`,
      `For those who love the System, the soul is surely lost`,
      `[Outro]`,
      `The vault is open`,
      `The lie is exposed`,
      `Perfect hatred for the sin`,
      `Perfect love for the Father`,
      `Come, every brother, drink the living water`,
      `Come, every sister, drink the living water`,
      `[THEOLOGICAL ANALYSIS SUMMARY]`,
      `Psalm 139 Theology*: Direct theological application of Psalm 139:21-22 ("Do not I hate them, O Lord, that hate thee? ... I hate them with perfect hatred: I count them mine enemies").`,
      `Exposing the System*: Identifying the modern Babylon matrix ("systems run", "secret laws of vanity", "towers of the wolves") as the literal, orchestrated enemy of the Most High.`,
      `Separation and Judgment*: establishing a stark juxtaposition of perfect love for the Father alongside perfect hatred for the sin that`,
      `REMNANT SEED SOUND CERTIFIED ✓`,
      `binds "the System," warning that eschatological judgment is imminent.`,
      `REMNANT SEED SOUND CERTIFIED ✓`,
      `SONG 9: THE WATER MY MOTHER CARRIED (TESHUVAH)`,
      `(Production Style: Remnant Seed Sound. Meditative, acoustic-driven roots groove. Slower, reflective pacing suited for deep generational repentance and testimony.)`,
      `[Spoken Intro / Prophetic Vision Step]`,
      `I am the Prophet Gad.`,
      `This word came not from judgment of the mother—`,
      `but from her own lips opened by the Spirit.`,
      `She asked why the child lied without flinching.`,
      `The Eternal Father turned the mirror.`,
      `[Verse 1]`,
      `My mother filled a clay pot`,
      `With water that was never clean —`,
      `She said drink child this is how we live`,
      `She said swallow what you cannot see`,
      `I watched her smile at faces`,
      `While her true words stayed inside —`,
      `I thought that was just wisdom`,
      `I did not know it was the seed of a lie`,
      `[Pre-Chorus]`,
      `Eternal Father — I only did what I was shown`,
      `He said I know my daughter — but the seed has fully grown`,
      `[Chorus]`,
      `I carried the water my mother carried`,
      `Poured it into the cup I gave my child —`,
      `What I called survival You call bondage`,
      `What I called wisdom You call exile's guile`,
      `The water that I carried`,
      `Was never meant to quench —`,
      `Generation drinking poison`,
      `From the vessel from the trench`,
      `[Verse 2]`,
      `I crossed the border with a borrowed name`,
      `I told myself the cause was pure —`,
      `A mother's love can sanctify a sin`,
      `Or so the crossing made me sure`,
      `But she was watching from the backseat`,
      `She was learning every word —`,
      `Every paper every checkpoint`,
      `Every careful lie she heard`,
      `[Pre-Chorus]`,
      `Eternal Father — I was only trying to survive`,
      `He said I know my daughter — but what did you keep alive`,
      `[Chorus]`,
      `I carried the water my mother carried`,
      `Poured it into the cup I gave my child —`,
      `What I called survival You call bondage`,
      `What I called wisdom You call exile's guile`,
      `[Bridge]`,
      `She is not the villain of this story —`,
      `Neither am I neither was my mother's name —`,
      `But the pot must be broken on the threshold`,
      `Or the daughter's daughter drinks the same`,
      `I opened Scripture on the kitchen table`,
      `Set it down between her eyes and mine —`,
      `And in the silence I saw my own reflection`,
      `Staring back across that crooked line`,
      `[Verse 3]`,
      `Ezekiel said the son shall not carry`,
      `The full weight of his father's sin —`,
      `But if he walks the same road unrepented`,
      `Then the judgment falls on him`,
      `So this is teshuvah for the mother —`,
      `Not the child's correction but my own —`,
      `To lay down what I carried from my mother`,
      `Before I plant it deeper in the bone`,
      `[Pre-Chorus]`,
      `Eternal Father — can a mother's turning set the child free`,
      `He said this is exactly why I came — now follow Me`,
      `[Chorus]`,
      `I will not carry what my mother carried`,
      `I will break the cup before I pass it on —`,
      `What You call teshuvah I call mercy`,
      `What You call turning I call coming home`,
      `[Outro / Final Call]`,
      `Lay the vessel down lay the vessel down`,
      `What was cracked at the source cannot be handed on`,
      `Eternal Father knows Eternal Father knows`,
      `The chain stops here sow the truth — live`,
      `Come every daughter come every mother`,
      `The door is open while mercy lingers`,
      `[THEOLOGICAL ANALYSIS SUMMARY]`,
      `Ezekiel 18 Theology*: Direct scriptural application of Ezekiel 18:20 regarding generational sin—acknowledging that while the child does not bear the guilt of the parent, inheriting and repeating the sin brings judgment.`,
      `Teshuvah (Repentance): Emphasizing the absolute necessity of true teshuvah* (turning away) to break generational curses of deception.`,
      `The Illusion of Carnal Wisdom*: Exposing how Babylon frames deceit and survival tactics as "wisdom," while the Most High defines it as the seed of bondage ("exile's guile").`,
      `REMNANT SEED SOUND CERTIFIED ✓`,
    ],
  },
];
